### ISSUE TITLE
getMimetype() pulls entire file

### ISSUE THREAD

**Issue by hfig** [robgridley/flysystem-smb#6]
``getMimetype()`` currently reads the entire file into memory to determine the mime type. Reading an entire file, especially over a network connection can be expensive. Further, if the file is large, it will out-of-memory PHP.

See [PR-5](https://github.com/robgridley/flysystem-smb/pull/5) which proposes reading a 64KB chunk instead to determine the MIME type.

**Comment by robgridley** [comment]
Pull merged. Tests updated. v1.0.3 released.

Thanks.
